In [1]:
from google.colab import files
uploaded=files.upload()

Saving impurity.xlsx to impurity.xlsx


In [2]:
import pandas as pd
import numpy as np

df=pd.read_excel('impurity.xlsx')
df

age  income student credit_rating buys_computer
0    <=30    high      no          fair            no
1    <=30    high      no     excellent            no
2   31…40    high      no          fair           yes
3     >40  medium      no          fair           yes
4     >40     low     yes          fair           yes
5     >40     low     yes     excellent            no
6   31…40     low     yes     excellent           yes
7    <=30  medium      no          fair            no
8    <=30     low     yes          fair           yes
9     >40  medium     yes          fair           yes
10   <=30  medium     yes     excellent           yes
11  31…40  medium      no     excellent           yes
12  31…40    high     yes          fair           yes
13    >40  medium      no     excellent            no

In [3]:
class_counts = df['student'].value_counts()

total_instances = len(df)
prior_prob_yes = class_counts['yes'] / total_instances
prior_prob_no = class_counts['no'] / total_instances

# Print the results
print("Prior probability of buys_computer = yes:", prior_prob_yes)
print("Prior probability of buys_computer = no:", prior_prob_no)

Prior probability of buys_computer = yes: 0.5
Prior probability of buys_computer = no: 0.5


In [4]:
import pandas as pd
from sklearn.neighbors import KernelDensity
numerical_features = ['age']

for class_label in df['student'].unique():
    print(f"Class: {class_label}")
    for feature in numerical_features:

        data_subset = df[df['student'] == class_label][feature]
        data_subset = pd.to_numeric(data_subset, errors='coerce')  # Convert to numeric, coerce non-numeric to NaN
        data_subset = data_subset.dropna()  # Drop NaN values

        if not data_subset.empty:

            kde = KernelDensity(bandwidth=1.0, kernel='gaussian')
            kde.fit(data_subset.values.reshape(-1, 1))
            values_to_evaluate = [30, 35, 40]
            densities = np.exp(kde.score_samples(np.array(values_to_evaluate).reshape(-1, 1)))

            print(f"Feature: {feature}")
            print(f"Densities: {densities}")
            print(f"Any zero density: {any(d == 0 for d in densities)}")
            print()
        else:
            print(f"Feature: {feature} - No numeric values for this class")


Class: no
Feature: age - No numeric values for this class
Class: yes
Feature: age - No numeric values for this class


In [5]:
import pandas as pd
from scipy.stats import chi2_contingency

contingency_table = pd.crosstab(index=df['age'], columns=[df['income'], df['student'], df['buys_computer']])

chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print("Expected frequencies:")
print(expected)
alpha = 0.05
print("\nTest result:")
if p_value < alpha:
    print("Reject the null hypothesis. There is evidence of a significant association between the features.")
else:
    print("Fail to reject the null hypothesis. There is no significant association between the features.")


Chi-square statistic: 13.183333333333332
P-value: 0.5121412984045752
Degrees of freedom: 14
Expected frequencies:
[[0.57142857 0.28571429 0.28571429 0.28571429 0.85714286 0.57142857
  0.57142857 0.57142857]
 [0.71428571 0.35714286 0.35714286 0.35714286 1.07142857 0.71428571
  0.71428571 0.71428571]
 [0.71428571 0.35714286 0.35714286 0.35714286 1.07142857 0.71428571
  0.71428571 0.71428571]]

Test result:
Fail to reject the null hypothesis. There is no significant association between the features.


In [13]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Your data
data = [
    ['<=30', 'high', 'no', 'fair', 'no'],
    ['<=30', 'high', 'no', 'excellent', 'no'],
    ['31…40', 'high', 'no', 'fair', 'yes'],
    ['>40', 'medium', 'no', 'fair', 'yes'],
    ['>40', 'low', 'yes', 'fair', 'yes'],
    ['>40', 'low', 'yes', 'excellent', 'no'],
    ['31…40', 'low', 'yes', 'excellent', 'yes'],
    ['<=30', 'medium', 'no', 'fair', 'no'],
    ['<=30', 'low', 'yes', 'fair', 'yes'],
    ['>40', 'medium', 'yes', 'fair', 'yes'],
    ['<=30', 'medium', 'yes', 'excellent', 'yes'],
    ['31…40', 'medium', 'no', 'excellent', 'yes'],
    ['31…40', 'high', 'yes', 'fair', 'yes'],
    ['>40',	'medium',	'no',	'excellent'	,'no']
]

class_column_index = 4

X = np.array([row[:-1] for row in data])
y = np.array([row[class_column_index] for row in data])

label_encoders = [LabelEncoder() for _ in range(X.shape[1])]
for i in range(X.shape[1]):
    X[:, i] = label_encoders[i].fit_transform(X[:, i])

Tr_X, Te_X, Tr_y, Te_y = train_test_split(X, y, test_size=0.2, random_state=42)

model = CategoricalNB()
model.fit(Tr_X, Tr_y)

predictions = model.predict(Te_X)

accuracy = np.mean(predictions == Te_y)
print(f"Accuracy: {accuracy:.4f}")


Accuracy: 0.3333


In [14]:
from google.colab import files
uploaded=files.upload()

Saving embeddingsdata.xlsx to embeddingsdata.xlsx


In [15]:
import pandas as pd
import numpy as np

df=pd.read_excel('embeddingsdata.xlsx')
df

embed_0   embed_1   embed_2   embed_3   embed_4   embed_5   embed_6  \
0    0.009625 -0.029216  0.027109  0.023631 -0.004972  0.031757 -0.045125   
1   -0.007535 -0.039844  0.030167  0.031224  0.004742  0.028289 -0.068723   
2    0.022408 -0.030840  0.032328  0.046965  0.007798  0.025860 -0.065093   
3    0.019677 -0.034055  0.012662  0.070387 -0.011170  0.017842 -0.050945   
4    0.017678 -0.030323  0.012829  0.065267 -0.025161  0.011964 -0.050590   
..        ...       ...       ...       ...       ...       ...       ...   
895  0.019743 -0.071799  0.022546  0.049042 -0.005767 -0.016275 -0.037731   
896  0.000186 -0.027604  0.010623  0.038237 -0.026675  0.020215 -0.040816   
897  0.018066 -0.032152  0.039794  0.047608  0.003898  0.024092 -0.056508   
898 -0.003492 -0.022739  0.021777  0.044054 -0.005621  0.013863 -0.079196   
899  0.013689 -0.037855  0.039763  0.035750  0.004115  0.005637 -0.050556   

      embed_7   embed_8   embed_9  ...  embed_759  embed_760  embed_761  \
0    0.044483  0.019400 -0.017189  ...  -0.001972  -0.008154  -0.056139   
1    0.039153  0.019596 -0.027138  ...   0.008613  -0.006578  -0.034220   
2    0.035118  0.035359 -0.029205  ...   0.020413  -0.034288  -0.050649   
3    0.044878  0.034781 -0.025772  ...   0.002963  -0.018754  -0.053278   
4    0.042820  0.029161 -0.015004  ...   0.010192  -0.010147  -0.035857   
..        ...       ...       ...  ...        ...        ...        ...   
895  0.029718  0.009203 -0.030913  ...  -0.001192  -0.026138  -0.056447   
896  0.032210  0.041016 -0.014836  ...   0.015479  -0.003967  -0.037808   
897  0.020527  0.031972 -0.026038  ...   0.011308  -0.016882  -0.059904   
898  0.039150  0.004557 -0.015787  ...   0.004005  -0.007196  -0.041652   
899  0.024668  0.025077 -0.029114  ...  -0.000129  -0.003880  -0.048696   

     embed_762  embed_763  embed_764  embed_765  embed_766  embed_767  Label  
0     0.009890   0.042366   0.040134   0.009304  -0.016137  -0.009309      0  
1     0.027574   0.045456   0.027402   0.017837  -0.035009  -0.010062      0  
2     0.028408   0.040412   0.030261   0.003535  -0.034122  -0.017289      0  
3     0.033005   0.031635   0.022544  -0.011774  -0.011125  -0.017540      0  
4     0.021784   0.034621   0.017342  -0.009884  -0.010316  -0.029238      0  
..         ...        ...        ...        ...        ...        ...    ...  
895   0.015818   0.045241   0.012620  -0.004837  -0.014540  -0.046791      2  
896   0.021234   0.031012  -0.010890   0.003081  -0.015145  -0.045444      0  
897   0.009558   0.039976   0.029574   0.013737  -0.003724  -0.017324      2  
898   0.020945   0.047604   0.019767   0.005806  -0.019280  -0.016415      5  
899   0.015711   0.039773   0.036328   0.010483  -0.021304  -0.032017      2  

[900 rows x 769 columns]

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import CategoricalNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
X =df.iloc[:,0:768]
y =df.iloc[:,768]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = CategoricalNB()
model.fit(X_train, y_train)
predictions = model.predict(X_test)

accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy:.4f}")

# Additional evaluation metrics
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))


Accuracy: 0.3778
              precision    recall  f1-score   support

           0       0.38      1.00      0.55        68
           1       0.00      0.00      0.00        52
           2       0.00      0.00      0.00        23
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         5
           5       0.00      0.00      0.00        12
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         2
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         6
          10       0.00      0.00      0.00         4

    accuracy                           0.38       180
   macro avg       0.03      0.09      0.05       180
weighted avg       0.14      0.38      0.21       180

[[68  0  0  0  0  0  0  0  0  0  0]
 [52  0  0  0  0  0  0  0  0  0  0]
 [23  0  0  0  0  0  0  0  0  0  0]
 [ 3  0  0  0  0  0  0  0  0  0  0]
 [ 5  0  0  0  0  0  0  0 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
